[package]
name = "usb2snes-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.0", default-features = false, features = ["napi8", "napi9"] }
napi-derive = "2.0"
serialport = "4.5"

[build-dependencies]
napi-build = "2.0"

